[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
fizzcaps_onchain = "5bhhmQTNNMGZdCnEBwKASCryF5g9cUbboeQJ7gEXuXMH"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "node tests/test.js"
