// backend/api/grok/generate-avatar.js
// -----------------------------------------------------------------------
// Atomic Fizz Caps – Grok Avatar Generation API
// POST /api/grok/generate-avatar → Generate Fallout-style avatar via xAI Grok
// -----------------------------------------------------------------------
'use strict';

const express = require('express');
const router  = express.Router();
const https = require('https');
const crypto = require('crypto');
const path = require('path');
const fs = require('fs');

const { authMiddleware } = require('../../lib/auth');

// Rate limit avatar generation to prevent API abuse
const rateLimit = require('express-rate-limit');
const avatarLimiter = rateLimit({
  windowMs: 60 * 1000, // 1 minute
  max: 3, // 3 avatars per minute per wallet
  keyGenerator: (req) => (req.player && req.player.wallet) || req.ip,
  message: { error: 'Too many avatar generation requests — take it easy, Vault Dweller' },
  standardHeaders: true,
  legacyHeaders: false,
});

// Input validation
function validateAvatarRequest(body) {
  if (!body || typeof body !== 'object') {
    return { valid: false, error: 'Request body must be an object' };
  }

  const { prompt, style } = body;

  if (!prompt || typeof prompt !== 'string' || prompt.length < 10 || prompt.length > 500) {
    return { valid: false, error: 'Prompt must be a string between 10-500 characters' };
  }

  if (style && style !== 'fallout-wasteland-survivor') {
    return { valid: false, error: 'Style must be "fallout-wasteland-survivor"' };
  }

  return { valid: true };
}

// Make request to xAI Grok API
async function makeGrokRequest(prompt) {
  return new Promise((resolve, reject) => {
    const systemPrompt = `You are a Fallout wasteland avatar generator. Create detailed, vivid descriptions of survivors in the Fallout universe. Focus on post-apocalyptic aesthetics, radiation damage, wasteland attire, cybernetic enhancements, and gritty survival gear. Keep descriptions under 200 words.`;

    const userPrompt = `Generate a detailed description for a Fallout wasteland survivor avatar based on this prompt: "${prompt}". Include appearance, clothing, gear, and any mutations or cybernetics. Make it authentic to the Fallout aesthetic.`;

    const postData = JSON.stringify({
      messages: [
        { role: "system", content: systemPrompt },
        { role: "user", content: userPrompt }
      ],
      model: "grok-beta",
      stream: false,
      temperature: 0.8,
      max_tokens: 300
    });

    const options = {
      hostname: 'api.x.ai',
      port: 443,
      path: '/v1/chat/completions',
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${process.env.XAI_API_KEY || 'dummy-key'}`,
        'Content-Length': Buffer.byteLength(postData)
      },
      timeout: 30000
    };

    const req = https.request(options, (res) => {
      let data = '';

      res.on('data', (chunk) => {
        data += chunk;
      });

      res.on('end', () => {
        try {
          const response = JSON.parse(data);

          if (res.statusCode !== 200) {
            reject(new Error(`Grok API error: ${res.statusCode} - ${response.error?.message || 'Unknown error'}`));
            return;
          }

          const description = response.choices?.[0]?.message?.content;
          if (!description) {
            reject(new Error('No description generated by Grok'));
            return;
          }

          resolve(description.trim());
        } catch (error) {
          reject(new Error(`Failed to parse Grok response: ${error.message}`));
        }
      });
    });

    req.on('error', (error) => {
      reject(new Error(`Grok API request failed: ${error.message}`));
    });

    req.on('timeout', () => {
      req.destroy();
      reject(new Error('Grok API request timed out'));
    });

    req.write(postData);
    req.end();
  });
}

// Generate unique avatar ID
function generateAvatarId() {
  return crypto.randomBytes(16).toString('hex');
}

// Save avatar description to manifest
function saveAvatarToManifest(description, avatarId) {
  const manifestPath = path.join(__dirname, '../../../public/assets/avatars-grok/manifest.json');

  try {
    let manifest = { avatars: [], totalAvatars: 0 };

    if (fs.existsSync(manifestPath)) {
      const manifestData = fs.readFileSync(manifestPath, 'utf8');
      manifest = JSON.parse(manifestData);
    }

    // Add new avatar
    manifest.avatars.push({
      id: avatarId,
      description: description,
      created: new Date().toISOString(),
      style: 'fallout-wasteland-survivor'
    });

    manifest.totalAvatars = manifest.avatars.length;

    // Save manifest
    fs.writeFileSync(manifestPath, JSON.stringify(manifest, null, 2));

    return true;
  } catch (error) {
    console.error('[GrokAvatar] Failed to save avatar to manifest:', error);
    return false;
  }
}

// POST /api/grok/generate-avatar
router.post('/generate-avatar', avatarLimiter, authMiddleware, async (req, res) => {
  try {
    // Validate request
    const validation = validateAvatarRequest(req.body);
    if (!validation.valid) {
      return res.status(400).json({ error: validation.error });
    }

    const { prompt } = req.body;

    // Generate description via Grok
    console.log(`[GrokAvatar] Generating avatar for wallet ${req.player.wallet}: ${prompt.substring(0, 50)}...`);

    const description = await makeGrokRequest(prompt);

    // Generate unique ID and save to manifest
    const avatarId = generateAvatarId();
    const saved = saveAvatarToManifest(description, avatarId);

    if (!saved) {
      return res.status(500).json({ error: 'Failed to save avatar' });
    }

    // Return avatar URL (description-based for now, could be enhanced with image generation)
    const avatarUrl = `/assets/avatars-grok/${avatarId}.json`;

    console.log(`[GrokAvatar] Generated avatar ${avatarId} for ${req.player.wallet}`);

    res.json({
      avatarUrl,
      description,
      avatarId
    });

  } catch (error) {
    console.error('[GrokAvatar] Generation failed:', error);

    // Return a fallback response instead of error for better UX
    res.status(500).json({
      error: 'Avatar generation temporarily unavailable',
      fallback: 'A grizzled wasteland survivor with tattered leather armor and a makeshift plasma rifle.'
    });
  }
});

module.exports = router;